// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ns_protobuf.proto

#ifndef PROTOBUF_INCLUDED_ns_5fprotobuf_2eproto
#define PROTOBUF_INCLUDED_ns_5fprotobuf_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ns_5fprotobuf_2eproto 

namespace protobuf_ns_5fprotobuf_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ns_5fprotobuf_2eproto
namespace Routn {
namespace Ns {
class Node;
class NodeDefaultTypeInternal;
extern NodeDefaultTypeInternal _Node_default_instance_;
class NodeInfo;
class NodeInfoDefaultTypeInternal;
extern NodeInfoDefaultTypeInternal _NodeInfo_default_instance_;
class NotifyMessage;
class NotifyMessageDefaultTypeInternal;
extern NotifyMessageDefaultTypeInternal _NotifyMessage_default_instance_;
class QueryRequest;
class QueryRequestDefaultTypeInternal;
extern QueryRequestDefaultTypeInternal _QueryRequest_default_instance_;
class QueryResponse;
class QueryResponseDefaultTypeInternal;
extern QueryResponseDefaultTypeInternal _QueryResponse_default_instance_;
class RegisterInfo;
class RegisterInfoDefaultTypeInternal;
extern RegisterInfoDefaultTypeInternal _RegisterInfo_default_instance_;
class RegisterRequest;
class RegisterRequestDefaultTypeInternal;
extern RegisterRequestDefaultTypeInternal _RegisterRequest_default_instance_;
}  // namespace Ns
}  // namespace Routn
namespace google {
namespace protobuf {
template<> ::Routn::Ns::Node* Arena::CreateMaybeMessage<::Routn::Ns::Node>(Arena*);
template<> ::Routn::Ns::NodeInfo* Arena::CreateMaybeMessage<::Routn::Ns::NodeInfo>(Arena*);
template<> ::Routn::Ns::NotifyMessage* Arena::CreateMaybeMessage<::Routn::Ns::NotifyMessage>(Arena*);
template<> ::Routn::Ns::QueryRequest* Arena::CreateMaybeMessage<::Routn::Ns::QueryRequest>(Arena*);
template<> ::Routn::Ns::QueryResponse* Arena::CreateMaybeMessage<::Routn::Ns::QueryResponse>(Arena*);
template<> ::Routn::Ns::RegisterInfo* Arena::CreateMaybeMessage<::Routn::Ns::RegisterInfo>(Arena*);
template<> ::Routn::Ns::RegisterRequest* Arena::CreateMaybeMessage<::Routn::Ns::RegisterRequest>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Routn {
namespace Ns {

// ===================================================================

class Node : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Routn.Ns.Node) */ {
 public:
  Node();
  virtual ~Node();

  Node(const Node& from);

  inline Node& operator=(const Node& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Node(Node&& from) noexcept
    : Node() {
    *this = ::std::move(from);
  }

  inline Node& operator=(Node&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Node& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Node* internal_default_instance() {
    return reinterpret_cast<const Node*>(
               &_Node_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Node* other);
  friend void swap(Node& a, Node& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Node* New() const final {
    return CreateMaybeMessage<Node>(NULL);
  }

  Node* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Node>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Node& from);
  void MergeFrom(const Node& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Node* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string ip = 1;
  bool has_ip() const;
  void clear_ip();
  static const int kIpFieldNumber = 1;
  const ::std::string& ip() const;
  void set_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_ip(::std::string&& value);
  #endif
  void set_ip(const char* value);
  void set_ip(const char* value, size_t size);
  ::std::string* mutable_ip();
  ::std::string* release_ip();
  void set_allocated_ip(::std::string* ip);

  // optional uint32 port = 2;
  bool has_port() const;
  void clear_port();
  static const int kPortFieldNumber = 2;
  ::google::protobuf::uint32 port() const;
  void set_port(::google::protobuf::uint32 value);

  // optional uint32 weight = 3;
  bool has_weight() const;
  void clear_weight();
  static const int kWeightFieldNumber = 3;
  ::google::protobuf::uint32 weight() const;
  void set_weight(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Routn.Ns.Node)
 private:
  void set_has_ip();
  void clear_has_ip();
  void set_has_port();
  void clear_has_port();
  void set_has_weight();
  void clear_has_weight();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr ip_;
  ::google::protobuf::uint32 port_;
  ::google::protobuf::uint32 weight_;
  friend struct ::protobuf_ns_5fprotobuf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RegisterInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Routn.Ns.RegisterInfo) */ {
 public:
  RegisterInfo();
  virtual ~RegisterInfo();

  RegisterInfo(const RegisterInfo& from);

  inline RegisterInfo& operator=(const RegisterInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RegisterInfo(RegisterInfo&& from) noexcept
    : RegisterInfo() {
    *this = ::std::move(from);
  }

  inline RegisterInfo& operator=(RegisterInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegisterInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterInfo* internal_default_instance() {
    return reinterpret_cast<const RegisterInfo*>(
               &_RegisterInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(RegisterInfo* other);
  friend void swap(RegisterInfo& a, RegisterInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RegisterInfo* New() const final {
    return CreateMaybeMessage<RegisterInfo>(NULL);
  }

  RegisterInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RegisterInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RegisterInfo& from);
  void MergeFrom(const RegisterInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegisterInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 cmds = 2;
  int cmds_size() const;
  void clear_cmds();
  static const int kCmdsFieldNumber = 2;
  ::google::protobuf::uint32 cmds(int index) const;
  void set_cmds(int index, ::google::protobuf::uint32 value);
  void add_cmds(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      cmds() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_cmds();

  // optional string domain = 1;
  bool has_domain() const;
  void clear_domain();
  static const int kDomainFieldNumber = 1;
  const ::std::string& domain() const;
  void set_domain(const ::std::string& value);
  #if LANG_CXX11
  void set_domain(::std::string&& value);
  #endif
  void set_domain(const char* value);
  void set_domain(const char* value, size_t size);
  ::std::string* mutable_domain();
  ::std::string* release_domain();
  void set_allocated_domain(::std::string* domain);

  // optional .Routn.Ns.Node node = 3;
  bool has_node() const;
  void clear_node();
  static const int kNodeFieldNumber = 3;
  private:
  const ::Routn::Ns::Node& _internal_node() const;
  public:
  const ::Routn::Ns::Node& node() const;
  ::Routn::Ns::Node* release_node();
  ::Routn::Ns::Node* mutable_node();
  void set_allocated_node(::Routn::Ns::Node* node);

  // @@protoc_insertion_point(class_scope:Routn.Ns.RegisterInfo)
 private:
  void set_has_domain();
  void clear_has_domain();
  void set_has_node();
  void clear_has_node();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > cmds_;
  ::google::protobuf::internal::ArenaStringPtr domain_;
  ::Routn::Ns::Node* node_;
  friend struct ::protobuf_ns_5fprotobuf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RegisterRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Routn.Ns.RegisterRequest) */ {
 public:
  RegisterRequest();
  virtual ~RegisterRequest();

  RegisterRequest(const RegisterRequest& from);

  inline RegisterRequest& operator=(const RegisterRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RegisterRequest(RegisterRequest&& from) noexcept
    : RegisterRequest() {
    *this = ::std::move(from);
  }

  inline RegisterRequest& operator=(RegisterRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegisterRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterRequest* internal_default_instance() {
    return reinterpret_cast<const RegisterRequest*>(
               &_RegisterRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(RegisterRequest* other);
  friend void swap(RegisterRequest& a, RegisterRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RegisterRequest* New() const final {
    return CreateMaybeMessage<RegisterRequest>(NULL);
  }

  RegisterRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RegisterRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RegisterRequest& from);
  void MergeFrom(const RegisterRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegisterRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Routn.Ns.RegisterInfo info = 1;
  int info_size() const;
  void clear_info();
  static const int kInfoFieldNumber = 1;
  ::Routn::Ns::RegisterInfo* mutable_info(int index);
  ::google::protobuf::RepeatedPtrField< ::Routn::Ns::RegisterInfo >*
      mutable_info();
  const ::Routn::Ns::RegisterInfo& info(int index) const;
  ::Routn::Ns::RegisterInfo* add_info();
  const ::google::protobuf::RepeatedPtrField< ::Routn::Ns::RegisterInfo >&
      info() const;

  // @@protoc_insertion_point(class_scope:Routn.Ns.RegisterRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Routn::Ns::RegisterInfo > info_;
  friend struct ::protobuf_ns_5fprotobuf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class QueryRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Routn.Ns.QueryRequest) */ {
 public:
  QueryRequest();
  virtual ~QueryRequest();

  QueryRequest(const QueryRequest& from);

  inline QueryRequest& operator=(const QueryRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  QueryRequest(QueryRequest&& from) noexcept
    : QueryRequest() {
    *this = ::std::move(from);
  }

  inline QueryRequest& operator=(QueryRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const QueryRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const QueryRequest* internal_default_instance() {
    return reinterpret_cast<const QueryRequest*>(
               &_QueryRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(QueryRequest* other);
  friend void swap(QueryRequest& a, QueryRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline QueryRequest* New() const final {
    return CreateMaybeMessage<QueryRequest>(NULL);
  }

  QueryRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<QueryRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const QueryRequest& from);
  void MergeFrom(const QueryRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QueryRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string domains = 1;
  int domains_size() const;
  void clear_domains();
  static const int kDomainsFieldNumber = 1;
  const ::std::string& domains(int index) const;
  ::std::string* mutable_domains(int index);
  void set_domains(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_domains(int index, ::std::string&& value);
  #endif
  void set_domains(int index, const char* value);
  void set_domains(int index, const char* value, size_t size);
  ::std::string* add_domains();
  void add_domains(const ::std::string& value);
  #if LANG_CXX11
  void add_domains(::std::string&& value);
  #endif
  void add_domains(const char* value);
  void add_domains(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& domains() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_domains();

  // @@protoc_insertion_point(class_scope:Routn.Ns.QueryRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> domains_;
  friend struct ::protobuf_ns_5fprotobuf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NodeInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Routn.Ns.NodeInfo) */ {
 public:
  NodeInfo();
  virtual ~NodeInfo();

  NodeInfo(const NodeInfo& from);

  inline NodeInfo& operator=(const NodeInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NodeInfo(NodeInfo&& from) noexcept
    : NodeInfo() {
    *this = ::std::move(from);
  }

  inline NodeInfo& operator=(NodeInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NodeInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NodeInfo* internal_default_instance() {
    return reinterpret_cast<const NodeInfo*>(
               &_NodeInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(NodeInfo* other);
  friend void swap(NodeInfo& a, NodeInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NodeInfo* New() const final {
    return CreateMaybeMessage<NodeInfo>(NULL);
  }

  NodeInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NodeInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NodeInfo& from);
  void MergeFrom(const NodeInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NodeInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Routn.Ns.Node nodes = 3;
  int nodes_size() const;
  void clear_nodes();
  static const int kNodesFieldNumber = 3;
  ::Routn::Ns::Node* mutable_nodes(int index);
  ::google::protobuf::RepeatedPtrField< ::Routn::Ns::Node >*
      mutable_nodes();
  const ::Routn::Ns::Node& nodes(int index) const;
  ::Routn::Ns::Node* add_nodes();
  const ::google::protobuf::RepeatedPtrField< ::Routn::Ns::Node >&
      nodes() const;

  // optional string domain = 1;
  bool has_domain() const;
  void clear_domain();
  static const int kDomainFieldNumber = 1;
  const ::std::string& domain() const;
  void set_domain(const ::std::string& value);
  #if LANG_CXX11
  void set_domain(::std::string&& value);
  #endif
  void set_domain(const char* value);
  void set_domain(const char* value, size_t size);
  ::std::string* mutable_domain();
  ::std::string* release_domain();
  void set_allocated_domain(::std::string* domain);

  // optional uint32 cmd = 2;
  bool has_cmd() const;
  void clear_cmd();
  static const int kCmdFieldNumber = 2;
  ::google::protobuf::uint32 cmd() const;
  void set_cmd(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Routn.Ns.NodeInfo)
 private:
  void set_has_domain();
  void clear_has_domain();
  void set_has_cmd();
  void clear_has_cmd();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Routn::Ns::Node > nodes_;
  ::google::protobuf::internal::ArenaStringPtr domain_;
  ::google::protobuf::uint32 cmd_;
  friend struct ::protobuf_ns_5fprotobuf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class QueryResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Routn.Ns.QueryResponse) */ {
 public:
  QueryResponse();
  virtual ~QueryResponse();

  QueryResponse(const QueryResponse& from);

  inline QueryResponse& operator=(const QueryResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  QueryResponse(QueryResponse&& from) noexcept
    : QueryResponse() {
    *this = ::std::move(from);
  }

  inline QueryResponse& operator=(QueryResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const QueryResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const QueryResponse* internal_default_instance() {
    return reinterpret_cast<const QueryResponse*>(
               &_QueryResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(QueryResponse* other);
  friend void swap(QueryResponse& a, QueryResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline QueryResponse* New() const final {
    return CreateMaybeMessage<QueryResponse>(NULL);
  }

  QueryResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<QueryResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const QueryResponse& from);
  void MergeFrom(const QueryResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QueryResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Routn.Ns.NodeInfo infos = 1;
  int infos_size() const;
  void clear_infos();
  static const int kInfosFieldNumber = 1;
  ::Routn::Ns::NodeInfo* mutable_infos(int index);
  ::google::protobuf::RepeatedPtrField< ::Routn::Ns::NodeInfo >*
      mutable_infos();
  const ::Routn::Ns::NodeInfo& infos(int index) const;
  ::Routn::Ns::NodeInfo* add_infos();
  const ::google::protobuf::RepeatedPtrField< ::Routn::Ns::NodeInfo >&
      infos() const;

  // @@protoc_insertion_point(class_scope:Routn.Ns.QueryResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Routn::Ns::NodeInfo > infos_;
  friend struct ::protobuf_ns_5fprotobuf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NotifyMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Routn.Ns.NotifyMessage) */ {
 public:
  NotifyMessage();
  virtual ~NotifyMessage();

  NotifyMessage(const NotifyMessage& from);

  inline NotifyMessage& operator=(const NotifyMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NotifyMessage(NotifyMessage&& from) noexcept
    : NotifyMessage() {
    *this = ::std::move(from);
  }

  inline NotifyMessage& operator=(NotifyMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NotifyMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NotifyMessage* internal_default_instance() {
    return reinterpret_cast<const NotifyMessage*>(
               &_NotifyMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(NotifyMessage* other);
  friend void swap(NotifyMessage& a, NotifyMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NotifyMessage* New() const final {
    return CreateMaybeMessage<NotifyMessage>(NULL);
  }

  NotifyMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NotifyMessage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NotifyMessage& from);
  void MergeFrom(const NotifyMessage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NotifyMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Routn.Ns.NodeInfo dels = 1;
  int dels_size() const;
  void clear_dels();
  static const int kDelsFieldNumber = 1;
  ::Routn::Ns::NodeInfo* mutable_dels(int index);
  ::google::protobuf::RepeatedPtrField< ::Routn::Ns::NodeInfo >*
      mutable_dels();
  const ::Routn::Ns::NodeInfo& dels(int index) const;
  ::Routn::Ns::NodeInfo* add_dels();
  const ::google::protobuf::RepeatedPtrField< ::Routn::Ns::NodeInfo >&
      dels() const;

  // repeated .Routn.Ns.NodeInfo updates = 2;
  int updates_size() const;
  void clear_updates();
  static const int kUpdatesFieldNumber = 2;
  ::Routn::Ns::NodeInfo* mutable_updates(int index);
  ::google::protobuf::RepeatedPtrField< ::Routn::Ns::NodeInfo >*
      mutable_updates();
  const ::Routn::Ns::NodeInfo& updates(int index) const;
  ::Routn::Ns::NodeInfo* add_updates();
  const ::google::protobuf::RepeatedPtrField< ::Routn::Ns::NodeInfo >&
      updates() const;

  // @@protoc_insertion_point(class_scope:Routn.Ns.NotifyMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Routn::Ns::NodeInfo > dels_;
  ::google::protobuf::RepeatedPtrField< ::Routn::Ns::NodeInfo > updates_;
  friend struct ::protobuf_ns_5fprotobuf_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Node

// optional string ip = 1;
inline bool Node::has_ip() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Node::set_has_ip() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Node::clear_has_ip() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Node::clear_ip() {
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_ip();
}
inline const ::std::string& Node::ip() const {
  // @@protoc_insertion_point(field_get:Routn.Ns.Node.ip)
  return ip_.GetNoArena();
}
inline void Node::set_ip(const ::std::string& value) {
  set_has_ip();
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Routn.Ns.Node.ip)
}
#if LANG_CXX11
inline void Node::set_ip(::std::string&& value) {
  set_has_ip();
  ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Routn.Ns.Node.ip)
}
#endif
inline void Node::set_ip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_ip();
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Routn.Ns.Node.ip)
}
inline void Node::set_ip(const char* value, size_t size) {
  set_has_ip();
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Routn.Ns.Node.ip)
}
inline ::std::string* Node::mutable_ip() {
  set_has_ip();
  // @@protoc_insertion_point(field_mutable:Routn.Ns.Node.ip)
  return ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Node::release_ip() {
  // @@protoc_insertion_point(field_release:Routn.Ns.Node.ip)
  if (!has_ip()) {
    return NULL;
  }
  clear_has_ip();
  return ip_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Node::set_allocated_ip(::std::string* ip) {
  if (ip != NULL) {
    set_has_ip();
  } else {
    clear_has_ip();
  }
  ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip);
  // @@protoc_insertion_point(field_set_allocated:Routn.Ns.Node.ip)
}

// optional uint32 port = 2;
inline bool Node::has_port() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Node::set_has_port() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Node::clear_has_port() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Node::clear_port() {
  port_ = 0u;
  clear_has_port();
}
inline ::google::protobuf::uint32 Node::port() const {
  // @@protoc_insertion_point(field_get:Routn.Ns.Node.port)
  return port_;
}
inline void Node::set_port(::google::protobuf::uint32 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:Routn.Ns.Node.port)
}

// optional uint32 weight = 3;
inline bool Node::has_weight() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Node::set_has_weight() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Node::clear_has_weight() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Node::clear_weight() {
  weight_ = 0u;
  clear_has_weight();
}
inline ::google::protobuf::uint32 Node::weight() const {
  // @@protoc_insertion_point(field_get:Routn.Ns.Node.weight)
  return weight_;
}
inline void Node::set_weight(::google::protobuf::uint32 value) {
  set_has_weight();
  weight_ = value;
  // @@protoc_insertion_point(field_set:Routn.Ns.Node.weight)
}

// -------------------------------------------------------------------

// RegisterInfo

// optional string domain = 1;
inline bool RegisterInfo::has_domain() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegisterInfo::set_has_domain() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegisterInfo::clear_has_domain() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegisterInfo::clear_domain() {
  domain_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_domain();
}
inline const ::std::string& RegisterInfo::domain() const {
  // @@protoc_insertion_point(field_get:Routn.Ns.RegisterInfo.domain)
  return domain_.GetNoArena();
}
inline void RegisterInfo::set_domain(const ::std::string& value) {
  set_has_domain();
  domain_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Routn.Ns.RegisterInfo.domain)
}
#if LANG_CXX11
inline void RegisterInfo::set_domain(::std::string&& value) {
  set_has_domain();
  domain_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Routn.Ns.RegisterInfo.domain)
}
#endif
inline void RegisterInfo::set_domain(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_domain();
  domain_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Routn.Ns.RegisterInfo.domain)
}
inline void RegisterInfo::set_domain(const char* value, size_t size) {
  set_has_domain();
  domain_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Routn.Ns.RegisterInfo.domain)
}
inline ::std::string* RegisterInfo::mutable_domain() {
  set_has_domain();
  // @@protoc_insertion_point(field_mutable:Routn.Ns.RegisterInfo.domain)
  return domain_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RegisterInfo::release_domain() {
  // @@protoc_insertion_point(field_release:Routn.Ns.RegisterInfo.domain)
  if (!has_domain()) {
    return NULL;
  }
  clear_has_domain();
  return domain_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RegisterInfo::set_allocated_domain(::std::string* domain) {
  if (domain != NULL) {
    set_has_domain();
  } else {
    clear_has_domain();
  }
  domain_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), domain);
  // @@protoc_insertion_point(field_set_allocated:Routn.Ns.RegisterInfo.domain)
}

// repeated uint32 cmds = 2;
inline int RegisterInfo::cmds_size() const {
  return cmds_.size();
}
inline void RegisterInfo::clear_cmds() {
  cmds_.Clear();
}
inline ::google::protobuf::uint32 RegisterInfo::cmds(int index) const {
  // @@protoc_insertion_point(field_get:Routn.Ns.RegisterInfo.cmds)
  return cmds_.Get(index);
}
inline void RegisterInfo::set_cmds(int index, ::google::protobuf::uint32 value) {
  cmds_.Set(index, value);
  // @@protoc_insertion_point(field_set:Routn.Ns.RegisterInfo.cmds)
}
inline void RegisterInfo::add_cmds(::google::protobuf::uint32 value) {
  cmds_.Add(value);
  // @@protoc_insertion_point(field_add:Routn.Ns.RegisterInfo.cmds)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
RegisterInfo::cmds() const {
  // @@protoc_insertion_point(field_list:Routn.Ns.RegisterInfo.cmds)
  return cmds_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
RegisterInfo::mutable_cmds() {
  // @@protoc_insertion_point(field_mutable_list:Routn.Ns.RegisterInfo.cmds)
  return &cmds_;
}

// optional .Routn.Ns.Node node = 3;
inline bool RegisterInfo::has_node() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RegisterInfo::set_has_node() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RegisterInfo::clear_has_node() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RegisterInfo::clear_node() {
  if (node_ != NULL) node_->Clear();
  clear_has_node();
}
inline const ::Routn::Ns::Node& RegisterInfo::_internal_node() const {
  return *node_;
}
inline const ::Routn::Ns::Node& RegisterInfo::node() const {
  const ::Routn::Ns::Node* p = node_;
  // @@protoc_insertion_point(field_get:Routn.Ns.RegisterInfo.node)
  return p != NULL ? *p : *reinterpret_cast<const ::Routn::Ns::Node*>(
      &::Routn::Ns::_Node_default_instance_);
}
inline ::Routn::Ns::Node* RegisterInfo::release_node() {
  // @@protoc_insertion_point(field_release:Routn.Ns.RegisterInfo.node)
  clear_has_node();
  ::Routn::Ns::Node* temp = node_;
  node_ = NULL;
  return temp;
}
inline ::Routn::Ns::Node* RegisterInfo::mutable_node() {
  set_has_node();
  if (node_ == NULL) {
    auto* p = CreateMaybeMessage<::Routn::Ns::Node>(GetArenaNoVirtual());
    node_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Routn.Ns.RegisterInfo.node)
  return node_;
}
inline void RegisterInfo::set_allocated_node(::Routn::Ns::Node* node) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete node_;
  }
  if (node) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      node = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, node, submessage_arena);
    }
    set_has_node();
  } else {
    clear_has_node();
  }
  node_ = node;
  // @@protoc_insertion_point(field_set_allocated:Routn.Ns.RegisterInfo.node)
}

// -------------------------------------------------------------------

// RegisterRequest

// repeated .Routn.Ns.RegisterInfo info = 1;
inline int RegisterRequest::info_size() const {
  return info_.size();
}
inline void RegisterRequest::clear_info() {
  info_.Clear();
}
inline ::Routn::Ns::RegisterInfo* RegisterRequest::mutable_info(int index) {
  // @@protoc_insertion_point(field_mutable:Routn.Ns.RegisterRequest.info)
  return info_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Routn::Ns::RegisterInfo >*
RegisterRequest::mutable_info() {
  // @@protoc_insertion_point(field_mutable_list:Routn.Ns.RegisterRequest.info)
  return &info_;
}
inline const ::Routn::Ns::RegisterInfo& RegisterRequest::info(int index) const {
  // @@protoc_insertion_point(field_get:Routn.Ns.RegisterRequest.info)
  return info_.Get(index);
}
inline ::Routn::Ns::RegisterInfo* RegisterRequest::add_info() {
  // @@protoc_insertion_point(field_add:Routn.Ns.RegisterRequest.info)
  return info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Routn::Ns::RegisterInfo >&
RegisterRequest::info() const {
  // @@protoc_insertion_point(field_list:Routn.Ns.RegisterRequest.info)
  return info_;
}

// -------------------------------------------------------------------

// QueryRequest

// repeated string domains = 1;
inline int QueryRequest::domains_size() const {
  return domains_.size();
}
inline void QueryRequest::clear_domains() {
  domains_.Clear();
}
inline const ::std::string& QueryRequest::domains(int index) const {
  // @@protoc_insertion_point(field_get:Routn.Ns.QueryRequest.domains)
  return domains_.Get(index);
}
inline ::std::string* QueryRequest::mutable_domains(int index) {
  // @@protoc_insertion_point(field_mutable:Routn.Ns.QueryRequest.domains)
  return domains_.Mutable(index);
}
inline void QueryRequest::set_domains(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Routn.Ns.QueryRequest.domains)
  domains_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void QueryRequest::set_domains(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:Routn.Ns.QueryRequest.domains)
  domains_.Mutable(index)->assign(std::move(value));
}
#endif
inline void QueryRequest::set_domains(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  domains_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Routn.Ns.QueryRequest.domains)
}
inline void QueryRequest::set_domains(int index, const char* value, size_t size) {
  domains_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Routn.Ns.QueryRequest.domains)
}
inline ::std::string* QueryRequest::add_domains() {
  // @@protoc_insertion_point(field_add_mutable:Routn.Ns.QueryRequest.domains)
  return domains_.Add();
}
inline void QueryRequest::add_domains(const ::std::string& value) {
  domains_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Routn.Ns.QueryRequest.domains)
}
#if LANG_CXX11
inline void QueryRequest::add_domains(::std::string&& value) {
  domains_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:Routn.Ns.QueryRequest.domains)
}
#endif
inline void QueryRequest::add_domains(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  domains_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Routn.Ns.QueryRequest.domains)
}
inline void QueryRequest::add_domains(const char* value, size_t size) {
  domains_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Routn.Ns.QueryRequest.domains)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
QueryRequest::domains() const {
  // @@protoc_insertion_point(field_list:Routn.Ns.QueryRequest.domains)
  return domains_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
QueryRequest::mutable_domains() {
  // @@protoc_insertion_point(field_mutable_list:Routn.Ns.QueryRequest.domains)
  return &domains_;
}

// -------------------------------------------------------------------

// NodeInfo

// optional string domain = 1;
inline bool NodeInfo::has_domain() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NodeInfo::set_has_domain() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NodeInfo::clear_has_domain() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NodeInfo::clear_domain() {
  domain_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_domain();
}
inline const ::std::string& NodeInfo::domain() const {
  // @@protoc_insertion_point(field_get:Routn.Ns.NodeInfo.domain)
  return domain_.GetNoArena();
}
inline void NodeInfo::set_domain(const ::std::string& value) {
  set_has_domain();
  domain_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Routn.Ns.NodeInfo.domain)
}
#if LANG_CXX11
inline void NodeInfo::set_domain(::std::string&& value) {
  set_has_domain();
  domain_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Routn.Ns.NodeInfo.domain)
}
#endif
inline void NodeInfo::set_domain(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_domain();
  domain_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Routn.Ns.NodeInfo.domain)
}
inline void NodeInfo::set_domain(const char* value, size_t size) {
  set_has_domain();
  domain_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Routn.Ns.NodeInfo.domain)
}
inline ::std::string* NodeInfo::mutable_domain() {
  set_has_domain();
  // @@protoc_insertion_point(field_mutable:Routn.Ns.NodeInfo.domain)
  return domain_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NodeInfo::release_domain() {
  // @@protoc_insertion_point(field_release:Routn.Ns.NodeInfo.domain)
  if (!has_domain()) {
    return NULL;
  }
  clear_has_domain();
  return domain_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NodeInfo::set_allocated_domain(::std::string* domain) {
  if (domain != NULL) {
    set_has_domain();
  } else {
    clear_has_domain();
  }
  domain_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), domain);
  // @@protoc_insertion_point(field_set_allocated:Routn.Ns.NodeInfo.domain)
}

// optional uint32 cmd = 2;
inline bool NodeInfo::has_cmd() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NodeInfo::set_has_cmd() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NodeInfo::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NodeInfo::clear_cmd() {
  cmd_ = 0u;
  clear_has_cmd();
}
inline ::google::protobuf::uint32 NodeInfo::cmd() const {
  // @@protoc_insertion_point(field_get:Routn.Ns.NodeInfo.cmd)
  return cmd_;
}
inline void NodeInfo::set_cmd(::google::protobuf::uint32 value) {
  set_has_cmd();
  cmd_ = value;
  // @@protoc_insertion_point(field_set:Routn.Ns.NodeInfo.cmd)
}

// repeated .Routn.Ns.Node nodes = 3;
inline int NodeInfo::nodes_size() const {
  return nodes_.size();
}
inline void NodeInfo::clear_nodes() {
  nodes_.Clear();
}
inline ::Routn::Ns::Node* NodeInfo::mutable_nodes(int index) {
  // @@protoc_insertion_point(field_mutable:Routn.Ns.NodeInfo.nodes)
  return nodes_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Routn::Ns::Node >*
NodeInfo::mutable_nodes() {
  // @@protoc_insertion_point(field_mutable_list:Routn.Ns.NodeInfo.nodes)
  return &nodes_;
}
inline const ::Routn::Ns::Node& NodeInfo::nodes(int index) const {
  // @@protoc_insertion_point(field_get:Routn.Ns.NodeInfo.nodes)
  return nodes_.Get(index);
}
inline ::Routn::Ns::Node* NodeInfo::add_nodes() {
  // @@protoc_insertion_point(field_add:Routn.Ns.NodeInfo.nodes)
  return nodes_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Routn::Ns::Node >&
NodeInfo::nodes() const {
  // @@protoc_insertion_point(field_list:Routn.Ns.NodeInfo.nodes)
  return nodes_;
}

// -------------------------------------------------------------------

// QueryResponse

// repeated .Routn.Ns.NodeInfo infos = 1;
inline int QueryResponse::infos_size() const {
  return infos_.size();
}
inline void QueryResponse::clear_infos() {
  infos_.Clear();
}
inline ::Routn::Ns::NodeInfo* QueryResponse::mutable_infos(int index) {
  // @@protoc_insertion_point(field_mutable:Routn.Ns.QueryResponse.infos)
  return infos_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Routn::Ns::NodeInfo >*
QueryResponse::mutable_infos() {
  // @@protoc_insertion_point(field_mutable_list:Routn.Ns.QueryResponse.infos)
  return &infos_;
}
inline const ::Routn::Ns::NodeInfo& QueryResponse::infos(int index) const {
  // @@protoc_insertion_point(field_get:Routn.Ns.QueryResponse.infos)
  return infos_.Get(index);
}
inline ::Routn::Ns::NodeInfo* QueryResponse::add_infos() {
  // @@protoc_insertion_point(field_add:Routn.Ns.QueryResponse.infos)
  return infos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Routn::Ns::NodeInfo >&
QueryResponse::infos() const {
  // @@protoc_insertion_point(field_list:Routn.Ns.QueryResponse.infos)
  return infos_;
}

// -------------------------------------------------------------------

// NotifyMessage

// repeated .Routn.Ns.NodeInfo dels = 1;
inline int NotifyMessage::dels_size() const {
  return dels_.size();
}
inline void NotifyMessage::clear_dels() {
  dels_.Clear();
}
inline ::Routn::Ns::NodeInfo* NotifyMessage::mutable_dels(int index) {
  // @@protoc_insertion_point(field_mutable:Routn.Ns.NotifyMessage.dels)
  return dels_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Routn::Ns::NodeInfo >*
NotifyMessage::mutable_dels() {
  // @@protoc_insertion_point(field_mutable_list:Routn.Ns.NotifyMessage.dels)
  return &dels_;
}
inline const ::Routn::Ns::NodeInfo& NotifyMessage::dels(int index) const {
  // @@protoc_insertion_point(field_get:Routn.Ns.NotifyMessage.dels)
  return dels_.Get(index);
}
inline ::Routn::Ns::NodeInfo* NotifyMessage::add_dels() {
  // @@protoc_insertion_point(field_add:Routn.Ns.NotifyMessage.dels)
  return dels_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Routn::Ns::NodeInfo >&
NotifyMessage::dels() const {
  // @@protoc_insertion_point(field_list:Routn.Ns.NotifyMessage.dels)
  return dels_;
}

// repeated .Routn.Ns.NodeInfo updates = 2;
inline int NotifyMessage::updates_size() const {
  return updates_.size();
}
inline void NotifyMessage::clear_updates() {
  updates_.Clear();
}
inline ::Routn::Ns::NodeInfo* NotifyMessage::mutable_updates(int index) {
  // @@protoc_insertion_point(field_mutable:Routn.Ns.NotifyMessage.updates)
  return updates_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Routn::Ns::NodeInfo >*
NotifyMessage::mutable_updates() {
  // @@protoc_insertion_point(field_mutable_list:Routn.Ns.NotifyMessage.updates)
  return &updates_;
}
inline const ::Routn::Ns::NodeInfo& NotifyMessage::updates(int index) const {
  // @@protoc_insertion_point(field_get:Routn.Ns.NotifyMessage.updates)
  return updates_.Get(index);
}
inline ::Routn::Ns::NodeInfo* NotifyMessage::add_updates() {
  // @@protoc_insertion_point(field_add:Routn.Ns.NotifyMessage.updates)
  return updates_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Routn::Ns::NodeInfo >&
NotifyMessage::updates() const {
  // @@protoc_insertion_point(field_list:Routn.Ns.NotifyMessage.updates)
  return updates_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Ns
}  // namespace Routn

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ns_5fprotobuf_2eproto
