# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rotun-li/routn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rotun-li/routn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rotun-li/routn/CMakeFiles /home/rotun-li/routn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rotun-li/routn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chat

# Build rule for target.
chat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chat
.PHONY : chat

# fast build rule for target.
chat/fast:
	$(MAKE) -f CMakeFiles/chat.dir/build.make CMakeFiles/chat.dir/build
.PHONY : chat/fast

#=============================================================================
# Target rules for targets named heart

# Build rule for target.
heart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heart
.PHONY : heart

# fast build rule for target.
heart/fast:
	$(MAKE) -f CMakeFiles/heart.dir/build.make CMakeFiles/heart.dir/build
.PHONY : heart/fast

#=============================================================================
# Target rules for targets named http_server_demo

# Build rule for target.
http_server_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_server_demo
.PHONY : http_server_demo

# fast build rule for target.
http_server_demo/fast:
	$(MAKE) -f CMakeFiles/http_server_demo.dir/build.make CMakeFiles/http_server_demo.dir/build
.PHONY : http_server_demo/fast

#=============================================================================
# Target rules for targets named test_http_connection

# Build rule for target.
test_http_connection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_connection
.PHONY : test_http_connection

# fast build rule for target.
test_http_connection/fast:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/build
.PHONY : test_http_connection/fast

#=============================================================================
# Target rules for targets named ex_echoServer

# Build rule for target.
ex_echoServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ex_echoServer
.PHONY : ex_echoServer

# fast build rule for target.
ex_echoServer/fast:
	$(MAKE) -f CMakeFiles/ex_echoServer.dir/build.make CMakeFiles/ex_echoServer.dir/build
.PHONY : ex_echoServer/fast

#=============================================================================
# Target rules for targets named routn-svr

# Build rule for target.
routn-svr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 routn-svr
.PHONY : routn-svr

# fast build rule for target.
routn-svr/fast:
	$(MAKE) -f CMakeFiles/routn-svr.dir/build.make CMakeFiles/routn-svr.dir/build
.PHONY : routn-svr/fast

#=============================================================================
# Target rules for targets named routn

# Build rule for target.
routn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 routn
.PHONY : routn

# fast build rule for target.
routn/fast:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/build
.PHONY : routn/fast

examples/ex_echoServer.o: examples/ex_echoServer.cpp.o

.PHONY : examples/ex_echoServer.o

# target to build an object file
examples/ex_echoServer.cpp.o:
	$(MAKE) -f CMakeFiles/ex_echoServer.dir/build.make CMakeFiles/ex_echoServer.dir/examples/ex_echoServer.cpp.o
.PHONY : examples/ex_echoServer.cpp.o

examples/ex_echoServer.i: examples/ex_echoServer.cpp.i

.PHONY : examples/ex_echoServer.i

# target to preprocess a source file
examples/ex_echoServer.cpp.i:
	$(MAKE) -f CMakeFiles/ex_echoServer.dir/build.make CMakeFiles/ex_echoServer.dir/examples/ex_echoServer.cpp.i
.PHONY : examples/ex_echoServer.cpp.i

examples/ex_echoServer.s: examples/ex_echoServer.cpp.s

.PHONY : examples/ex_echoServer.s

# target to generate assembly for a file
examples/ex_echoServer.cpp.s:
	$(MAKE) -f CMakeFiles/ex_echoServer.dir/build.make CMakeFiles/ex_echoServer.dir/examples/ex_echoServer.cpp.s
.PHONY : examples/ex_echoServer.cpp.s

examples/http_server_demo.o: examples/http_server_demo.cpp.o

.PHONY : examples/http_server_demo.o

# target to build an object file
examples/http_server_demo.cpp.o:
	$(MAKE) -f CMakeFiles/http_server_demo.dir/build.make CMakeFiles/http_server_demo.dir/examples/http_server_demo.cpp.o
.PHONY : examples/http_server_demo.cpp.o

examples/http_server_demo.i: examples/http_server_demo.cpp.i

.PHONY : examples/http_server_demo.i

# target to preprocess a source file
examples/http_server_demo.cpp.i:
	$(MAKE) -f CMakeFiles/http_server_demo.dir/build.make CMakeFiles/http_server_demo.dir/examples/http_server_demo.cpp.i
.PHONY : examples/http_server_demo.cpp.i

examples/http_server_demo.s: examples/http_server_demo.cpp.s

.PHONY : examples/http_server_demo.s

# target to generate assembly for a file
examples/http_server_demo.cpp.s:
	$(MAKE) -f CMakeFiles/http_server_demo.dir/build.make CMakeFiles/http_server_demo.dir/examples/http_server_demo.cpp.s
.PHONY : examples/http_server_demo.cpp.s

modules/chat_room/chat_module.o: modules/chat_room/chat_module.cpp.o

.PHONY : modules/chat_room/chat_module.o

# target to build an object file
modules/chat_room/chat_module.cpp.o:
	$(MAKE) -f CMakeFiles/chat.dir/build.make CMakeFiles/chat.dir/modules/chat_room/chat_module.cpp.o
.PHONY : modules/chat_room/chat_module.cpp.o

modules/chat_room/chat_module.i: modules/chat_room/chat_module.cpp.i

.PHONY : modules/chat_room/chat_module.i

# target to preprocess a source file
modules/chat_room/chat_module.cpp.i:
	$(MAKE) -f CMakeFiles/chat.dir/build.make CMakeFiles/chat.dir/modules/chat_room/chat_module.cpp.i
.PHONY : modules/chat_room/chat_module.cpp.i

modules/chat_room/chat_module.s: modules/chat_room/chat_module.cpp.s

.PHONY : modules/chat_room/chat_module.s

# target to generate assembly for a file
modules/chat_room/chat_module.cpp.s:
	$(MAKE) -f CMakeFiles/chat.dir/build.make CMakeFiles/chat.dir/modules/chat_room/chat_module.cpp.s
.PHONY : modules/chat_room/chat_module.cpp.s

modules/chat_room/chat_servlet.o: modules/chat_room/chat_servlet.cpp.o

.PHONY : modules/chat_room/chat_servlet.o

# target to build an object file
modules/chat_room/chat_servlet.cpp.o:
	$(MAKE) -f CMakeFiles/chat.dir/build.make CMakeFiles/chat.dir/modules/chat_room/chat_servlet.cpp.o
.PHONY : modules/chat_room/chat_servlet.cpp.o

modules/chat_room/chat_servlet.i: modules/chat_room/chat_servlet.cpp.i

.PHONY : modules/chat_room/chat_servlet.i

# target to preprocess a source file
modules/chat_room/chat_servlet.cpp.i:
	$(MAKE) -f CMakeFiles/chat.dir/build.make CMakeFiles/chat.dir/modules/chat_room/chat_servlet.cpp.i
.PHONY : modules/chat_room/chat_servlet.cpp.i

modules/chat_room/chat_servlet.s: modules/chat_room/chat_servlet.cpp.s

.PHONY : modules/chat_room/chat_servlet.s

# target to generate assembly for a file
modules/chat_room/chat_servlet.cpp.s:
	$(MAKE) -f CMakeFiles/chat.dir/build.make CMakeFiles/chat.dir/modules/chat_room/chat_servlet.cpp.s
.PHONY : modules/chat_room/chat_servlet.cpp.s

modules/heart/heart_module.o: modules/heart/heart_module.cpp.o

.PHONY : modules/heart/heart_module.o

# target to build an object file
modules/heart/heart_module.cpp.o:
	$(MAKE) -f CMakeFiles/heart.dir/build.make CMakeFiles/heart.dir/modules/heart/heart_module.cpp.o
.PHONY : modules/heart/heart_module.cpp.o

modules/heart/heart_module.i: modules/heart/heart_module.cpp.i

.PHONY : modules/heart/heart_module.i

# target to preprocess a source file
modules/heart/heart_module.cpp.i:
	$(MAKE) -f CMakeFiles/heart.dir/build.make CMakeFiles/heart.dir/modules/heart/heart_module.cpp.i
.PHONY : modules/heart/heart_module.cpp.i

modules/heart/heart_module.s: modules/heart/heart_module.cpp.s

.PHONY : modules/heart/heart_module.s

# target to generate assembly for a file
modules/heart/heart_module.cpp.s:
	$(MAKE) -f CMakeFiles/heart.dir/build.make CMakeFiles/heart.dir/modules/heart/heart_module.cpp.s
.PHONY : modules/heart/heart_module.cpp.s

src/Address.o: src/Address.cpp.o

.PHONY : src/Address.o

# target to build an object file
src/Address.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Address.cpp.o
.PHONY : src/Address.cpp.o

src/Address.i: src/Address.cpp.i

.PHONY : src/Address.i

# target to preprocess a source file
src/Address.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Address.cpp.i
.PHONY : src/Address.cpp.i

src/Address.s: src/Address.cpp.s

.PHONY : src/Address.s

# target to generate assembly for a file
src/Address.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Address.cpp.s
.PHONY : src/Address.cpp.s

src/Application.o: src/Application.cpp.o

.PHONY : src/Application.o

# target to build an object file
src/Application.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Application.cpp.o
.PHONY : src/Application.cpp.o

src/Application.i: src/Application.cpp.i

.PHONY : src/Application.i

# target to preprocess a source file
src/Application.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Application.cpp.i
.PHONY : src/Application.cpp.i

src/Application.s: src/Application.cpp.s

.PHONY : src/Application.s

# target to generate assembly for a file
src/Application.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Application.cpp.s
.PHONY : src/Application.cpp.s

src/ByteArray.o: src/ByteArray.cpp.o

.PHONY : src/ByteArray.o

# target to build an object file
src/ByteArray.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/ByteArray.cpp.o
.PHONY : src/ByteArray.cpp.o

src/ByteArray.i: src/ByteArray.cpp.i

.PHONY : src/ByteArray.i

# target to preprocess a source file
src/ByteArray.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/ByteArray.cpp.i
.PHONY : src/ByteArray.cpp.i

src/ByteArray.s: src/ByteArray.cpp.s

.PHONY : src/ByteArray.s

# target to generate assembly for a file
src/ByteArray.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/ByteArray.cpp.s
.PHONY : src/ByteArray.cpp.s

src/Config.o: src/Config.cpp.o

.PHONY : src/Config.o

# target to build an object file
src/Config.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Config.cpp.o
.PHONY : src/Config.cpp.o

src/Config.i: src/Config.cpp.i

.PHONY : src/Config.i

# target to preprocess a source file
src/Config.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Config.cpp.i
.PHONY : src/Config.cpp.i

src/Config.s: src/Config.cpp.s

.PHONY : src/Config.s

# target to generate assembly for a file
src/Config.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Config.cpp.s
.PHONY : src/Config.cpp.s

src/Daemon.o: src/Daemon.cpp.o

.PHONY : src/Daemon.o

# target to build an object file
src/Daemon.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Daemon.cpp.o
.PHONY : src/Daemon.cpp.o

src/Daemon.i: src/Daemon.cpp.i

.PHONY : src/Daemon.i

# target to preprocess a source file
src/Daemon.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Daemon.cpp.i
.PHONY : src/Daemon.cpp.i

src/Daemon.s: src/Daemon.cpp.s

.PHONY : src/Daemon.s

# target to generate assembly for a file
src/Daemon.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Daemon.cpp.s
.PHONY : src/Daemon.cpp.s

src/Dns.o: src/Dns.cpp.o

.PHONY : src/Dns.o

# target to build an object file
src/Dns.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Dns.cpp.o
.PHONY : src/Dns.cpp.o

src/Dns.i: src/Dns.cpp.i

.PHONY : src/Dns.i

# target to preprocess a source file
src/Dns.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Dns.cpp.i
.PHONY : src/Dns.cpp.i

src/Dns.s: src/Dns.cpp.s

.PHONY : src/Dns.s

# target to generate assembly for a file
src/Dns.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Dns.cpp.s
.PHONY : src/Dns.cpp.s

src/Env.o: src/Env.cpp.o

.PHONY : src/Env.o

# target to build an object file
src/Env.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Env.cpp.o
.PHONY : src/Env.cpp.o

src/Env.i: src/Env.cpp.i

.PHONY : src/Env.i

# target to preprocess a source file
src/Env.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Env.cpp.i
.PHONY : src/Env.cpp.i

src/Env.s: src/Env.cpp.s

.PHONY : src/Env.s

# target to generate assembly for a file
src/Env.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Env.cpp.s
.PHONY : src/Env.cpp.s

src/FdManager.o: src/FdManager.cpp.o

.PHONY : src/FdManager.o

# target to build an object file
src/FdManager.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/FdManager.cpp.o
.PHONY : src/FdManager.cpp.o

src/FdManager.i: src/FdManager.cpp.i

.PHONY : src/FdManager.i

# target to preprocess a source file
src/FdManager.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/FdManager.cpp.i
.PHONY : src/FdManager.cpp.i

src/FdManager.s: src/FdManager.cpp.s

.PHONY : src/FdManager.s

# target to generate assembly for a file
src/FdManager.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/FdManager.cpp.s
.PHONY : src/FdManager.cpp.s

src/Fiber.o: src/Fiber.cpp.o

.PHONY : src/Fiber.o

# target to build an object file
src/Fiber.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Fiber.cpp.o
.PHONY : src/Fiber.cpp.o

src/Fiber.i: src/Fiber.cpp.i

.PHONY : src/Fiber.i

# target to preprocess a source file
src/Fiber.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Fiber.cpp.i
.PHONY : src/Fiber.cpp.i

src/Fiber.s: src/Fiber.cpp.s

.PHONY : src/Fiber.s

# target to generate assembly for a file
src/Fiber.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Fiber.cpp.s
.PHONY : src/Fiber.cpp.s

src/FiberSem.o: src/FiberSem.cpp.o

.PHONY : src/FiberSem.o

# target to build an object file
src/FiberSem.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/FiberSem.cpp.o
.PHONY : src/FiberSem.cpp.o

src/FiberSem.i: src/FiberSem.cpp.i

.PHONY : src/FiberSem.i

# target to preprocess a source file
src/FiberSem.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/FiberSem.cpp.i
.PHONY : src/FiberSem.cpp.i

src/FiberSem.s: src/FiberSem.cpp.s

.PHONY : src/FiberSem.s

# target to generate assembly for a file
src/FiberSem.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/FiberSem.cpp.s
.PHONY : src/FiberSem.cpp.s

src/Hook.o: src/Hook.cpp.o

.PHONY : src/Hook.o

# target to build an object file
src/Hook.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Hook.cpp.o
.PHONY : src/Hook.cpp.o

src/Hook.i: src/Hook.cpp.i

.PHONY : src/Hook.i

# target to preprocess a source file
src/Hook.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Hook.cpp.i
.PHONY : src/Hook.cpp.i

src/Hook.s: src/Hook.cpp.s

.PHONY : src/Hook.s

# target to generate assembly for a file
src/Hook.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Hook.cpp.s
.PHONY : src/Hook.cpp.s

src/IoManager.o: src/IoManager.cpp.o

.PHONY : src/IoManager.o

# target to build an object file
src/IoManager.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/IoManager.cpp.o
.PHONY : src/IoManager.cpp.o

src/IoManager.i: src/IoManager.cpp.i

.PHONY : src/IoManager.i

# target to preprocess a source file
src/IoManager.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/IoManager.cpp.i
.PHONY : src/IoManager.cpp.i

src/IoManager.s: src/IoManager.cpp.s

.PHONY : src/IoManager.s

# target to generate assembly for a file
src/IoManager.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/IoManager.cpp.s
.PHONY : src/IoManager.cpp.s

src/Library.o: src/Library.cpp.o

.PHONY : src/Library.o

# target to build an object file
src/Library.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Library.cpp.o
.PHONY : src/Library.cpp.o

src/Library.i: src/Library.cpp.i

.PHONY : src/Library.i

# target to preprocess a source file
src/Library.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Library.cpp.i
.PHONY : src/Library.cpp.i

src/Library.s: src/Library.cpp.s

.PHONY : src/Library.s

# target to generate assembly for a file
src/Library.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Library.cpp.s
.PHONY : src/Library.cpp.s

src/Log.o: src/Log.cpp.o

.PHONY : src/Log.o

# target to build an object file
src/Log.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Log.cpp.o
.PHONY : src/Log.cpp.o

src/Log.i: src/Log.cpp.i

.PHONY : src/Log.i

# target to preprocess a source file
src/Log.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Log.cpp.i
.PHONY : src/Log.cpp.i

src/Log.s: src/Log.cpp.s

.PHONY : src/Log.s

# target to generate assembly for a file
src/Log.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Log.cpp.s
.PHONY : src/Log.cpp.s

src/Module.o: src/Module.cpp.o

.PHONY : src/Module.o

# target to build an object file
src/Module.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Module.cpp.o
.PHONY : src/Module.cpp.o

src/Module.i: src/Module.cpp.i

.PHONY : src/Module.i

# target to preprocess a source file
src/Module.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Module.cpp.i
.PHONY : src/Module.cpp.i

src/Module.s: src/Module.cpp.s

.PHONY : src/Module.s

# target to generate assembly for a file
src/Module.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Module.cpp.s
.PHONY : src/Module.cpp.s

src/Scheduler.o: src/Scheduler.cpp.o

.PHONY : src/Scheduler.o

# target to build an object file
src/Scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Scheduler.cpp.o
.PHONY : src/Scheduler.cpp.o

src/Scheduler.i: src/Scheduler.cpp.i

.PHONY : src/Scheduler.i

# target to preprocess a source file
src/Scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Scheduler.cpp.i
.PHONY : src/Scheduler.cpp.i

src/Scheduler.s: src/Scheduler.cpp.s

.PHONY : src/Scheduler.s

# target to generate assembly for a file
src/Scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Scheduler.cpp.s
.PHONY : src/Scheduler.cpp.s

src/Socket.o: src/Socket.cpp.o

.PHONY : src/Socket.o

# target to build an object file
src/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Socket.cpp.o
.PHONY : src/Socket.cpp.o

src/Socket.i: src/Socket.cpp.i

.PHONY : src/Socket.i

# target to preprocess a source file
src/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Socket.cpp.i
.PHONY : src/Socket.cpp.i

src/Socket.s: src/Socket.cpp.s

.PHONY : src/Socket.s

# target to generate assembly for a file
src/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Socket.cpp.s
.PHONY : src/Socket.cpp.s

src/SocketStream.o: src/SocketStream.cpp.o

.PHONY : src/SocketStream.o

# target to build an object file
src/SocketStream.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/SocketStream.cpp.o
.PHONY : src/SocketStream.cpp.o

src/SocketStream.i: src/SocketStream.cpp.i

.PHONY : src/SocketStream.i

# target to preprocess a source file
src/SocketStream.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/SocketStream.cpp.i
.PHONY : src/SocketStream.cpp.i

src/SocketStream.s: src/SocketStream.cpp.s

.PHONY : src/SocketStream.s

# target to generate assembly for a file
src/SocketStream.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/SocketStream.cpp.s
.PHONY : src/SocketStream.cpp.s

src/Stream.o: src/Stream.cpp.o

.PHONY : src/Stream.o

# target to build an object file
src/Stream.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Stream.cpp.o
.PHONY : src/Stream.cpp.o

src/Stream.i: src/Stream.cpp.i

.PHONY : src/Stream.i

# target to preprocess a source file
src/Stream.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Stream.cpp.i
.PHONY : src/Stream.cpp.i

src/Stream.s: src/Stream.cpp.s

.PHONY : src/Stream.s

# target to generate assembly for a file
src/Stream.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Stream.cpp.s
.PHONY : src/Stream.cpp.s

src/TcpServer.o: src/TcpServer.cpp.o

.PHONY : src/TcpServer.o

# target to build an object file
src/TcpServer.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/TcpServer.cpp.o
.PHONY : src/TcpServer.cpp.o

src/TcpServer.i: src/TcpServer.cpp.i

.PHONY : src/TcpServer.i

# target to preprocess a source file
src/TcpServer.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/TcpServer.cpp.i
.PHONY : src/TcpServer.cpp.i

src/TcpServer.s: src/TcpServer.cpp.s

.PHONY : src/TcpServer.s

# target to generate assembly for a file
src/TcpServer.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/TcpServer.cpp.s
.PHONY : src/TcpServer.cpp.s

src/Thread.o: src/Thread.cpp.o

.PHONY : src/Thread.o

# target to build an object file
src/Thread.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Thread.cpp.o
.PHONY : src/Thread.cpp.o

src/Thread.i: src/Thread.cpp.i

.PHONY : src/Thread.i

# target to preprocess a source file
src/Thread.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Thread.cpp.i
.PHONY : src/Thread.cpp.i

src/Thread.s: src/Thread.cpp.s

.PHONY : src/Thread.s

# target to generate assembly for a file
src/Thread.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Thread.cpp.s
.PHONY : src/Thread.cpp.s

src/Timer.o: src/Timer.cpp.o

.PHONY : src/Timer.o

# target to build an object file
src/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Timer.cpp.o
.PHONY : src/Timer.cpp.o

src/Timer.i: src/Timer.cpp.i

.PHONY : src/Timer.i

# target to preprocess a source file
src/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Timer.cpp.i
.PHONY : src/Timer.cpp.i

src/Timer.s: src/Timer.cpp.s

.PHONY : src/Timer.s

# target to generate assembly for a file
src/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Timer.cpp.s
.PHONY : src/Timer.cpp.s

src/Uri.rl.o: src/Uri.rl.cpp.o

.PHONY : src/Uri.rl.o

# target to build an object file
src/Uri.rl.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Uri.rl.cpp.o
.PHONY : src/Uri.rl.cpp.o

src/Uri.rl.i: src/Uri.rl.cpp.i

.PHONY : src/Uri.rl.i

# target to preprocess a source file
src/Uri.rl.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Uri.rl.cpp.i
.PHONY : src/Uri.rl.cpp.i

src/Uri.rl.s: src/Uri.rl.cpp.s

.PHONY : src/Uri.rl.s

# target to generate assembly for a file
src/Uri.rl.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Uri.rl.cpp.s
.PHONY : src/Uri.rl.cpp.s

src/Util.o: src/Util.cpp.o

.PHONY : src/Util.o

# target to build an object file
src/Util.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Util.cpp.o
.PHONY : src/Util.cpp.o

src/Util.i: src/Util.cpp.i

.PHONY : src/Util.i

# target to preprocess a source file
src/Util.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Util.cpp.i
.PHONY : src/Util.cpp.i

src/Util.s: src/Util.cpp.s

.PHONY : src/Util.s

# target to generate assembly for a file
src/Util.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Util.cpp.s
.PHONY : src/Util.cpp.s

src/Worker.o: src/Worker.cpp.o

.PHONY : src/Worker.o

# target to build an object file
src/Worker.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Worker.cpp.o
.PHONY : src/Worker.cpp.o

src/Worker.i: src/Worker.cpp.i

.PHONY : src/Worker.i

# target to preprocess a source file
src/Worker.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Worker.cpp.i
.PHONY : src/Worker.cpp.i

src/Worker.s: src/Worker.cpp.s

.PHONY : src/Worker.s

# target to generate assembly for a file
src/Worker.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/Worker.cpp.s
.PHONY : src/Worker.cpp.s

src/http/HTTP.o: src/http/HTTP.cpp.o

.PHONY : src/http/HTTP.o

# target to build an object file
src/http/HTTP.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/HTTP.cpp.o
.PHONY : src/http/HTTP.cpp.o

src/http/HTTP.i: src/http/HTTP.cpp.i

.PHONY : src/http/HTTP.i

# target to preprocess a source file
src/http/HTTP.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/HTTP.cpp.i
.PHONY : src/http/HTTP.cpp.i

src/http/HTTP.s: src/http/HTTP.cpp.s

.PHONY : src/http/HTTP.s

# target to generate assembly for a file
src/http/HTTP.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/HTTP.cpp.s
.PHONY : src/http/HTTP.cpp.s

src/http/HttpConnection.o: src/http/HttpConnection.cpp.o

.PHONY : src/http/HttpConnection.o

# target to build an object file
src/http/HttpConnection.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/HttpConnection.cpp.o
.PHONY : src/http/HttpConnection.cpp.o

src/http/HttpConnection.i: src/http/HttpConnection.cpp.i

.PHONY : src/http/HttpConnection.i

# target to preprocess a source file
src/http/HttpConnection.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/HttpConnection.cpp.i
.PHONY : src/http/HttpConnection.cpp.i

src/http/HttpConnection.s: src/http/HttpConnection.cpp.s

.PHONY : src/http/HttpConnection.s

# target to generate assembly for a file
src/http/HttpConnection.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/HttpConnection.cpp.s
.PHONY : src/http/HttpConnection.cpp.s

src/http/HttpServer.o: src/http/HttpServer.cpp.o

.PHONY : src/http/HttpServer.o

# target to build an object file
src/http/HttpServer.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/HttpServer.cpp.o
.PHONY : src/http/HttpServer.cpp.o

src/http/HttpServer.i: src/http/HttpServer.cpp.i

.PHONY : src/http/HttpServer.i

# target to preprocess a source file
src/http/HttpServer.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/HttpServer.cpp.i
.PHONY : src/http/HttpServer.cpp.i

src/http/HttpServer.s: src/http/HttpServer.cpp.s

.PHONY : src/http/HttpServer.s

# target to generate assembly for a file
src/http/HttpServer.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/HttpServer.cpp.s
.PHONY : src/http/HttpServer.cpp.s

src/http/HttpServlet.o: src/http/HttpServlet.cpp.o

.PHONY : src/http/HttpServlet.o

# target to build an object file
src/http/HttpServlet.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/HttpServlet.cpp.o
.PHONY : src/http/HttpServlet.cpp.o

src/http/HttpServlet.i: src/http/HttpServlet.cpp.i

.PHONY : src/http/HttpServlet.i

# target to preprocess a source file
src/http/HttpServlet.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/HttpServlet.cpp.i
.PHONY : src/http/HttpServlet.cpp.i

src/http/HttpServlet.s: src/http/HttpServlet.cpp.s

.PHONY : src/http/HttpServlet.s

# target to generate assembly for a file
src/http/HttpServlet.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/HttpServlet.cpp.s
.PHONY : src/http/HttpServlet.cpp.s

src/http/HttpSession.o: src/http/HttpSession.cpp.o

.PHONY : src/http/HttpSession.o

# target to build an object file
src/http/HttpSession.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/HttpSession.cpp.o
.PHONY : src/http/HttpSession.cpp.o

src/http/HttpSession.i: src/http/HttpSession.cpp.i

.PHONY : src/http/HttpSession.i

# target to preprocess a source file
src/http/HttpSession.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/HttpSession.cpp.i
.PHONY : src/http/HttpSession.cpp.i

src/http/HttpSession.s: src/http/HttpSession.cpp.s

.PHONY : src/http/HttpSession.s

# target to generate assembly for a file
src/http/HttpSession.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/HttpSession.cpp.s
.PHONY : src/http/HttpSession.cpp.s

src/http/Parser.o: src/http/Parser.cpp.o

.PHONY : src/http/Parser.o

# target to build an object file
src/http/Parser.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/Parser.cpp.o
.PHONY : src/http/Parser.cpp.o

src/http/Parser.i: src/http/Parser.cpp.i

.PHONY : src/http/Parser.i

# target to preprocess a source file
src/http/Parser.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/Parser.cpp.i
.PHONY : src/http/Parser.cpp.i

src/http/Parser.s: src/http/Parser.cpp.s

.PHONY : src/http/Parser.s

# target to generate assembly for a file
src/http/Parser.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/Parser.cpp.s
.PHONY : src/http/Parser.cpp.s

src/http/WSConnection.o: src/http/WSConnection.cpp.o

.PHONY : src/http/WSConnection.o

# target to build an object file
src/http/WSConnection.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/WSConnection.cpp.o
.PHONY : src/http/WSConnection.cpp.o

src/http/WSConnection.i: src/http/WSConnection.cpp.i

.PHONY : src/http/WSConnection.i

# target to preprocess a source file
src/http/WSConnection.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/WSConnection.cpp.i
.PHONY : src/http/WSConnection.cpp.i

src/http/WSConnection.s: src/http/WSConnection.cpp.s

.PHONY : src/http/WSConnection.s

# target to generate assembly for a file
src/http/WSConnection.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/WSConnection.cpp.s
.PHONY : src/http/WSConnection.cpp.s

src/http/WSServer.o: src/http/WSServer.cpp.o

.PHONY : src/http/WSServer.o

# target to build an object file
src/http/WSServer.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/WSServer.cpp.o
.PHONY : src/http/WSServer.cpp.o

src/http/WSServer.i: src/http/WSServer.cpp.i

.PHONY : src/http/WSServer.i

# target to preprocess a source file
src/http/WSServer.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/WSServer.cpp.i
.PHONY : src/http/WSServer.cpp.i

src/http/WSServer.s: src/http/WSServer.cpp.s

.PHONY : src/http/WSServer.s

# target to generate assembly for a file
src/http/WSServer.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/WSServer.cpp.s
.PHONY : src/http/WSServer.cpp.s

src/http/WSServlet.o: src/http/WSServlet.cpp.o

.PHONY : src/http/WSServlet.o

# target to build an object file
src/http/WSServlet.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/WSServlet.cpp.o
.PHONY : src/http/WSServlet.cpp.o

src/http/WSServlet.i: src/http/WSServlet.cpp.i

.PHONY : src/http/WSServlet.i

# target to preprocess a source file
src/http/WSServlet.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/WSServlet.cpp.i
.PHONY : src/http/WSServlet.cpp.i

src/http/WSServlet.s: src/http/WSServlet.cpp.s

.PHONY : src/http/WSServlet.s

# target to generate assembly for a file
src/http/WSServlet.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/WSServlet.cpp.s
.PHONY : src/http/WSServlet.cpp.s

src/http/WSSession.o: src/http/WSSession.cpp.o

.PHONY : src/http/WSSession.o

# target to build an object file
src/http/WSSession.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/WSSession.cpp.o
.PHONY : src/http/WSSession.cpp.o

src/http/WSSession.i: src/http/WSSession.cpp.i

.PHONY : src/http/WSSession.i

# target to preprocess a source file
src/http/WSSession.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/WSSession.cpp.i
.PHONY : src/http/WSSession.cpp.i

src/http/WSSession.s: src/http/WSSession.cpp.s

.PHONY : src/http/WSSession.s

# target to generate assembly for a file
src/http/WSSession.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/WSSession.cpp.s
.PHONY : src/http/WSSession.cpp.s

src/http/http11_parser.rl.o: src/http/http11_parser.rl.cpp.o

.PHONY : src/http/http11_parser.rl.o

# target to build an object file
src/http/http11_parser.rl.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/http11_parser.rl.cpp.o
.PHONY : src/http/http11_parser.rl.cpp.o

src/http/http11_parser.rl.i: src/http/http11_parser.rl.cpp.i

.PHONY : src/http/http11_parser.rl.i

# target to preprocess a source file
src/http/http11_parser.rl.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/http11_parser.rl.cpp.i
.PHONY : src/http/http11_parser.rl.cpp.i

src/http/http11_parser.rl.s: src/http/http11_parser.rl.cpp.s

.PHONY : src/http/http11_parser.rl.s

# target to generate assembly for a file
src/http/http11_parser.rl.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/http11_parser.rl.cpp.s
.PHONY : src/http/http11_parser.rl.cpp.s

src/http/httpclient_parser.rl.o: src/http/httpclient_parser.rl.cpp.o

.PHONY : src/http/httpclient_parser.rl.o

# target to build an object file
src/http/httpclient_parser.rl.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/httpclient_parser.rl.cpp.o
.PHONY : src/http/httpclient_parser.rl.cpp.o

src/http/httpclient_parser.rl.i: src/http/httpclient_parser.rl.cpp.i

.PHONY : src/http/httpclient_parser.rl.i

# target to preprocess a source file
src/http/httpclient_parser.rl.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/httpclient_parser.rl.cpp.i
.PHONY : src/http/httpclient_parser.rl.cpp.i

src/http/httpclient_parser.rl.s: src/http/httpclient_parser.rl.cpp.s

.PHONY : src/http/httpclient_parser.rl.s

# target to generate assembly for a file
src/http/httpclient_parser.rl.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/http/httpclient_parser.rl.cpp.s
.PHONY : src/http/httpclient_parser.rl.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/routn-svr.dir/build.make CMakeFiles/routn-svr.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/routn-svr.dir/build.make CMakeFiles/routn-svr.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/routn-svr.dir/build.make CMakeFiles/routn-svr.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/plugins/libco/coctx.o: src/plugins/libco/coctx.cpp.o

.PHONY : src/plugins/libco/coctx.o

# target to build an object file
src/plugins/libco/coctx.cpp.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/plugins/libco/coctx.cpp.o
.PHONY : src/plugins/libco/coctx.cpp.o

src/plugins/libco/coctx.i: src/plugins/libco/coctx.cpp.i

.PHONY : src/plugins/libco/coctx.i

# target to preprocess a source file
src/plugins/libco/coctx.cpp.i:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/plugins/libco/coctx.cpp.i
.PHONY : src/plugins/libco/coctx.cpp.i

src/plugins/libco/coctx.s: src/plugins/libco/coctx.cpp.s

.PHONY : src/plugins/libco/coctx.s

# target to generate assembly for a file
src/plugins/libco/coctx.cpp.s:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/plugins/libco/coctx.cpp.s
.PHONY : src/plugins/libco/coctx.cpp.s

src/plugins/libco/coctx_swap.o: src/plugins/libco/coctx_swap.S.o

.PHONY : src/plugins/libco/coctx_swap.o

# target to build an object file
src/plugins/libco/coctx_swap.S.o:
	$(MAKE) -f CMakeFiles/routn.dir/build.make CMakeFiles/routn.dir/src/plugins/libco/coctx_swap.S.o
.PHONY : src/plugins/libco/coctx_swap.S.o

test/test_http_connection.o: test/test_http_connection.cpp.o

.PHONY : test/test_http_connection.o

# target to build an object file
test/test_http_connection.cpp.o:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/test/test_http_connection.cpp.o
.PHONY : test/test_http_connection.cpp.o

test/test_http_connection.i: test/test_http_connection.cpp.i

.PHONY : test/test_http_connection.i

# target to preprocess a source file
test/test_http_connection.cpp.i:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/test/test_http_connection.cpp.i
.PHONY : test/test_http_connection.cpp.i

test/test_http_connection.s: test/test_http_connection.cpp.s

.PHONY : test/test_http_connection.s

# target to generate assembly for a file
test/test_http_connection.cpp.s:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/test/test_http_connection.cpp.s
.PHONY : test/test_http_connection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... chat"
	@echo "... rebuild_cache"
	@echo "... heart"
	@echo "... http_server_demo"
	@echo "... test_http_connection"
	@echo "... ex_echoServer"
	@echo "... routn-svr"
	@echo "... routn"
	@echo "... examples/ex_echoServer.o"
	@echo "... examples/ex_echoServer.i"
	@echo "... examples/ex_echoServer.s"
	@echo "... examples/http_server_demo.o"
	@echo "... examples/http_server_demo.i"
	@echo "... examples/http_server_demo.s"
	@echo "... modules/chat_room/chat_module.o"
	@echo "... modules/chat_room/chat_module.i"
	@echo "... modules/chat_room/chat_module.s"
	@echo "... modules/chat_room/chat_servlet.o"
	@echo "... modules/chat_room/chat_servlet.i"
	@echo "... modules/chat_room/chat_servlet.s"
	@echo "... modules/heart/heart_module.o"
	@echo "... modules/heart/heart_module.i"
	@echo "... modules/heart/heart_module.s"
	@echo "... src/Address.o"
	@echo "... src/Address.i"
	@echo "... src/Address.s"
	@echo "... src/Application.o"
	@echo "... src/Application.i"
	@echo "... src/Application.s"
	@echo "... src/ByteArray.o"
	@echo "... src/ByteArray.i"
	@echo "... src/ByteArray.s"
	@echo "... src/Config.o"
	@echo "... src/Config.i"
	@echo "... src/Config.s"
	@echo "... src/Daemon.o"
	@echo "... src/Daemon.i"
	@echo "... src/Daemon.s"
	@echo "... src/Dns.o"
	@echo "... src/Dns.i"
	@echo "... src/Dns.s"
	@echo "... src/Env.o"
	@echo "... src/Env.i"
	@echo "... src/Env.s"
	@echo "... src/FdManager.o"
	@echo "... src/FdManager.i"
	@echo "... src/FdManager.s"
	@echo "... src/Fiber.o"
	@echo "... src/Fiber.i"
	@echo "... src/Fiber.s"
	@echo "... src/FiberSem.o"
	@echo "... src/FiberSem.i"
	@echo "... src/FiberSem.s"
	@echo "... src/Hook.o"
	@echo "... src/Hook.i"
	@echo "... src/Hook.s"
	@echo "... src/IoManager.o"
	@echo "... src/IoManager.i"
	@echo "... src/IoManager.s"
	@echo "... src/Library.o"
	@echo "... src/Library.i"
	@echo "... src/Library.s"
	@echo "... src/Log.o"
	@echo "... src/Log.i"
	@echo "... src/Log.s"
	@echo "... src/Module.o"
	@echo "... src/Module.i"
	@echo "... src/Module.s"
	@echo "... src/Scheduler.o"
	@echo "... src/Scheduler.i"
	@echo "... src/Scheduler.s"
	@echo "... src/Socket.o"
	@echo "... src/Socket.i"
	@echo "... src/Socket.s"
	@echo "... src/SocketStream.o"
	@echo "... src/SocketStream.i"
	@echo "... src/SocketStream.s"
	@echo "... src/Stream.o"
	@echo "... src/Stream.i"
	@echo "... src/Stream.s"
	@echo "... src/TcpServer.o"
	@echo "... src/TcpServer.i"
	@echo "... src/TcpServer.s"
	@echo "... src/Thread.o"
	@echo "... src/Thread.i"
	@echo "... src/Thread.s"
	@echo "... src/Timer.o"
	@echo "... src/Timer.i"
	@echo "... src/Timer.s"
	@echo "... src/Uri.rl.o"
	@echo "... src/Uri.rl.i"
	@echo "... src/Uri.rl.s"
	@echo "... src/Util.o"
	@echo "... src/Util.i"
	@echo "... src/Util.s"
	@echo "... src/Worker.o"
	@echo "... src/Worker.i"
	@echo "... src/Worker.s"
	@echo "... src/http/HTTP.o"
	@echo "... src/http/HTTP.i"
	@echo "... src/http/HTTP.s"
	@echo "... src/http/HttpConnection.o"
	@echo "... src/http/HttpConnection.i"
	@echo "... src/http/HttpConnection.s"
	@echo "... src/http/HttpServer.o"
	@echo "... src/http/HttpServer.i"
	@echo "... src/http/HttpServer.s"
	@echo "... src/http/HttpServlet.o"
	@echo "... src/http/HttpServlet.i"
	@echo "... src/http/HttpServlet.s"
	@echo "... src/http/HttpSession.o"
	@echo "... src/http/HttpSession.i"
	@echo "... src/http/HttpSession.s"
	@echo "... src/http/Parser.o"
	@echo "... src/http/Parser.i"
	@echo "... src/http/Parser.s"
	@echo "... src/http/WSConnection.o"
	@echo "... src/http/WSConnection.i"
	@echo "... src/http/WSConnection.s"
	@echo "... src/http/WSServer.o"
	@echo "... src/http/WSServer.i"
	@echo "... src/http/WSServer.s"
	@echo "... src/http/WSServlet.o"
	@echo "... src/http/WSServlet.i"
	@echo "... src/http/WSServlet.s"
	@echo "... src/http/WSSession.o"
	@echo "... src/http/WSSession.i"
	@echo "... src/http/WSSession.s"
	@echo "... src/http/http11_parser.rl.o"
	@echo "... src/http/http11_parser.rl.i"
	@echo "... src/http/http11_parser.rl.s"
	@echo "... src/http/httpclient_parser.rl.o"
	@echo "... src/http/httpclient_parser.rl.i"
	@echo "... src/http/httpclient_parser.rl.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/plugins/libco/coctx.o"
	@echo "... src/plugins/libco/coctx.i"
	@echo "... src/plugins/libco/coctx.s"
	@echo "... src/plugins/libco/coctx_swap.o"
	@echo "... test/test_http_connection.o"
	@echo "... test/test_http_connection.i"
	@echo "... test/test_http_connection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

